# Generated by Django 6.0.1 on 2026-01-22 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(help_text='Exact name of the SOAP operation', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.role')),
            ],
            options={
                'unique_together': {('role', 'operation_name')},
            },
        ),
    ]
