# Generated by Django 6.0.3 on 2026-03-17 07:58

from django.db import migrations

def add_default_roles(apps, schema_editor):
    Role = apps.get_model('core', 'Role')
    roles_to_create = ['Admin', 'Manager', 'Underwriter']
    for role_name in roles_to_create:
        Role.objects.get_or_create(name=role_name)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_role_id_alter_roleoperation_id_and_more'),
    ]

    operations = [
        migrations.RunPython(add_default_roles)
    ]
